
statistics_attributes = [
    "num_wins",
    "num_draws",
    "num_losses",
    "win_defector_avg",
    "win_skipped_avg",
    "win_invalid_avg",
    "win_quit_avg",
    "draw_defector_avg",
    "draw_skipped_avg",
    "draw_invalid_avg",
    "draw_quit_avg",
    "loss_defector_avg",
    "loss_skipped_avg",
    "loss_invalid_avg",
    "loss_quit_avg",
    "avg_defectors",
    "avg_skipped",
    "avg_invalid",
    "avg_quit",
]
